# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required


matrix:
  include:
    - os: linux
      compiler: gcc
      r: release
      r_check_args: --as-cran --use-valgrind
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
          - valgrind
          - ['g++-9']
      env:
        - COMPILER=g++-9
        - CC=gcc=9
        - CXX=g++-9
        - CFLAGS="-g -O2 -Wall -pedantic -mtune=native"
        - FFLAGS="-g -O2 -mtune=native -Wall -pedantic"
        - CXXFLAGS="-g -O2 -Wall -pedantic -mtune=native -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-parentheses"
        - JAVA_HOME=/usr/lib/jvm/jre-11
        - AR=gcc-ar
        - RANLIB=gcc-ranlib

env:
 global:
   - CRAN: http://cran.rstudio.com
   
notifications:
  email:
    on_success: change
    on_failure: change